package JavaGuiLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.language.LanguageRegistry;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private final ConceptPresentation props_Element = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_Frame = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_IntegerAttribute = new ConceptPresentationBuilder().create();
  private final ConceptPresentation props_StringAttribute = new ConceptPresentationBuilder().create();

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) LanguageRegistry.getInstance().getLanguage(MetaAdapterFactory.getLanguage(SLanguageId.deserialize("48fa6eb6-1e16-4aa9-9b45-ecc67f930903"), "JavaGuiLanguage")).getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case 0:
        return props_Element;
      case 1:
        return props_Frame;
      case 2:
        return props_IntegerAttribute;
      case 3:
        return props_StringAttribute;
    }
    throw new IllegalStateException();
  }
}
