package JavaGuiLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.concept.SConceptAdapterById;
import jetbrains.mps.smodel.adapter.structure.concept.SInterfaceConceptAdapterById;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.SNodePointer;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  private final Map<SConceptId, Integer> myIndexMap = new HashMap<SConceptId, Integer>(4);
  /*package*/ final ConceptDescriptor myConceptElement = createDescriptorForElement();
  /*package*/ final ConceptDescriptor myConceptFrame = createDescriptorForFrame();
  /*package*/ final ConceptDescriptor myConceptIntegerAttribute = createDescriptorForIntegerAttribute();
  /*package*/ final ConceptDescriptor myConceptStringAttribute = createDescriptorForStringAttribute();

  public StructureAspectDescriptor() {
    myIndexMap.put(myConceptElement.getId(), 0);
    myIndexMap.put(myConceptFrame.getId(), 1);
    myIndexMap.put(myConceptIntegerAttribute.getId(), 2);
    myIndexMap.put(myConceptStringAttribute.getId(), 3);
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptElement, myConceptFrame, myConceptIntegerAttribute, myConceptStringAttribute);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    Integer index = myIndexMap.get(id);
    if (index == null) {
      return null;
    }
    switch (((int) index)) {
      case 0:
        return myConceptElement;
      case 1:
        return myConceptFrame;
      case 2:
        return myConceptIntegerAttribute;
      case 3:
        return myConceptStringAttribute;
      default:
        throw new IllegalStateException();
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    Integer res = null;
    if (c instanceof SConceptAdapterById) {
      res = myIndexMap.get(((SConceptAdapterById) c).getId());
    } else if (c instanceof SInterfaceConceptAdapterById) {
      res = myIndexMap.get(((SInterfaceConceptAdapterById) c).getId());
    }
    return (res == null ? -1 : res);
  }

  private static ConceptDescriptor createDescriptorForElement() {
    return new ConceptDescriptorBuilder("JavaGuiLanguage.structure.Element", MetaIdFactory.conceptId(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x27d4c529a7f40aedL, "intAttribute", MetaIdFactory.conceptId(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40088L), true, true, false, new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243968237")), new ConceptDescriptorBuilder.Link(0x27d4c529a7f47c3eL, "stringAttribute", MetaIdFactory.conceptId(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL), true, true, false, new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243997246"))).children(new String[]{"intAttribute", "stringAttribute"}, new boolean[]{true, true}).alias("Element", "This is Element").sourceNode(new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243968205")).create();
  }
  private static ConceptDescriptor createDescriptorForFrame() {
    return new ConceptDescriptorBuilder("JavaGuiLanguage.structure.Frame", MetaIdFactory.conceptId(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x27d4c529a7f4105cL, "intAttribute", MetaIdFactory.conceptId(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40088L), true, true, false, new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243969628")), new ConceptDescriptorBuilder.Link(0x27d4c529a7f4b962L, "stringAttribute", MetaIdFactory.conceptId(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL), true, true, false, new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645244012898")), new ConceptDescriptorBuilder.Link(0x27d4c529a7f41056L, "element", MetaIdFactory.conceptId(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL), true, true, false, new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243969622"))).children(new String[]{"intAttribute", "stringAttribute", "element"}, new boolean[]{true, true, true}).rootable().alias("Frame", "This is JFrame element").sourceNode(new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243831807")).create();
  }
  private static ConceptDescriptor createDescriptorForIntegerAttribute() {
    return new ConceptDescriptorBuilder("JavaGuiLanguage.structure.IntegerAttribute", MetaIdFactory.conceptId(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40088L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x27d4c529a7f400a1L, "value", new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243965601"))).properties("value").alias("Integer", "This is Integer attribute").sourceNode(new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243965576")).create();
  }
  private static ConceptDescriptor createDescriptorForStringAttribute() {
    return new ConceptDescriptorBuilder("JavaGuiLanguage.structure.StringAttribute", MetaIdFactory.conceptId(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.lang.core.structure.IDontSubstituteByDefault").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x19796fa16a19888bL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x27d4c529a7f3f87dL, "value", new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243963517"))).properties("value").alias("String", "This is String attribute").sourceNode(new SNodePointer("r:f49640b4-59a9-4b59-bf11-04898e8e776a(JavaGuiLanguage.structure)", "2870135645243963502")).create();
  }
}
