package JavaGuiSolution.TestModel;

/*Generated by MPS */

import javax.swing.JFrame;
import javax.swing.JPanel;
import java.awt.EventQueue;
import javax.swing.border.EmptyBorder;
import java.awt.FlowLayout;
import java.awt.Component;
import javax.swing.JButton;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextField;

public class Naslov extends JFrame {

  private JPanel contentPane;

  public static void main(String[] args) {
    EventQueue.invokeLater(new Runnable() {
      public void run() {
        try {
          Naslov frame = new Naslov();
          frame.setVisible(true);
        } catch (Exception e) {
          e.printStackTrace();
        }
      }
    });
  }

  public Naslov() {
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    setTitle("Naslov");
    setBounds(100, 100, 550, 400);

    setContentPaneProperties();
    addNewElement();


  }

  public void setContentPaneProperties() {
    contentPane = new JPanel();
    contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
    contentPane.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
    setContentPane(contentPane);
  }

  public void addNewElement() {
    contentPane.add(createNewComponent_a());
    contentPane.add(createNewComponent_b());
    contentPane.add(createNewComponent_c());
    contentPane.add(createNewComponent_d());
  }

  public Component createNewComponent_a() {
    JButton component = new JButton();

    component.setText("Button 1");
    component.setEnabled(false);
    component.setOpaque(true);
    component.setBackground(Color.red);
    return component;

  }
  public Component createNewComponent_b() {
    JLabel component = new JLabel();

    component.setText("Label 1");
    component.setEnabled(true);
    component.setOpaque(true);
    component.setBackground(Color.blue);
    return component;

  }
  public Component createNewComponent_c() {
    JTextField component = new JTextField();

    component.setFocusable(false);
    component.setText("Text Field 1");
    return component;

  }
  public Component createNewComponent_d() {
    JButton component = new JButton();

    component.setText("Button 2");
    return component;

  }
}
