package JavaGuiLanguage.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SModelOperations;
import jetbrains.mps.internal.collections.runtime.ITranslator2;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IWhereFilter;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_2870135645249708067(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Button");
  }
  public static boolean baseMappingRule_Condition_2870135645250614153(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Label");
  }
  public static boolean baseMappingRule_Condition_2870135645250617255(final BaseMappingRuleContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Text Field");
  }
  public static Object propertyMacro_GetPropertyValue_2870135645247694409(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4b962L, "stringAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Title");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL, 0x27d4c529a7f3f87dL, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_2870135645247931688(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4b962L, "stringAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Title");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL, 0x27d4c529a7f3f87dL, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_2870135645249135106(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4105cL, "intAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("BoundsX");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40088L, 0x27d4c529a7f400a1L, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_2870135645249135133(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4105cL, "intAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("BoundsY");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40088L, 0x27d4c529a7f400a1L, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_2870135645249135160(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4105cL, "intAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("BoundsWidth");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40088L, 0x27d4c529a7f400a1L, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_2870135645249135187(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger(ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4105cL, "intAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("BoundsHeight");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40088L, 0x27d4c529a7f400a1L, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_2870135645249529627(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL, 0x27d4c529a7f3f87dL, "value")).equals("true");
  }
  public static Object propertyMacro_GetPropertyValue_2870135645249671369(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Text");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL, 0x27d4c529a7f3f87dL, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_2870135645249622566(final PropertyMacroContext _context) {
    return _context.createUniqueName(_context.getTemplateValue(), null);
  }
  public static Object propertyMacro_GetPropertyValue_2870135645250327503(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Text");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL, 0x27d4c529a7f3f87dL, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_2870135645250327555(final PropertyMacroContext _context) {
    return _context.createUniqueName(_context.getTemplateValue(), null);
  }
  public static Object propertyMacro_GetPropertyValue_2870135645250368977(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Focusable");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL, 0x27d4c529a7f3f87dL, "value")).equals("true");
  }
  public static Object propertyMacro_GetPropertyValue_2870135645250335218(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Text");
      }
    }), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL, 0x27d4c529a7f3f87dL, "value"));
  }
  public static Object propertyMacro_GetPropertyValue_2870135645250335270(final PropertyMacroContext _context) {
    return _context.createUniqueName(_context.getTemplateValue(), null);
  }
  public static Object referenceMacro_GetReferent_2870135645249853455(final ReferenceMacroContext _context) {
    return _context.getOutputNodeByInputNodeAndMappingLabel(_context.getNode(), "method_mapping");
  }
  public static Object referenceMacro_GetReferent_2870135645249568559(final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), MetaAdapterFactory.getProperty(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f3f86eL, 0x27d4c529a7f3f87dL, "value"));
  }
  public static boolean ifMacro_Condition_2870135645249135213(final IfMacroContext _context) {
    return (ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4105cL, "intAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("BoundsX");
      }
    }) != null) && (ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4105cL, "intAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("BoundsY");
      }
    }) != null) && (ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4105cL, "intAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("BoundsWidth");
      }
    }) != null) && (ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f4105cL, "intAttribute"));
      }
    }).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("BoundsHeight");
      }
    }) != null);
  }
  public static boolean ifMacro_Condition_2870135645249640724(final IfMacroContext _context) {
    return (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Text");
      }
    }) != null);
  }
  public static boolean ifMacro_Condition_2870135645250327525(final IfMacroContext _context) {
    return (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Text");
      }
    }) != null);
  }
  public static boolean ifMacro_Condition_2870135645250353325(final IfMacroContext _context) {
    return (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Focusable");
      }
    }) != null);
  }
  public static boolean ifMacro_Condition_2870135645250335240(final IfMacroContext _context) {
    return (ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Text");
      }
    }) != null);
  }
  public static SNode sourceNodeQuery_2870135645249493859(final SourceSubstituteMacroNodeContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Enabled");
      }
    });
  }
  public static SNode sourceNodeQuery_2870135645250124105(final SourceSubstituteMacroNodeContext _context) {
    return ListSequence.fromList(SLinkOperations.getChildren(_context.getNode(), MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f40acdL, 0x27d4c529a7f47c3eL, "stringAttribute"))).findFirst(new IWhereFilter<SNode>() {
      public boolean accept(SNode it) {
        return SPropertyOperations.getString(it, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name")).equals("Background");
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_2870135645249877287(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f41056L, "element"));
      }
    });
  }
  public static Iterable<SNode> sourceNodesQuery_2870135645249808149(final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SModelOperations.roots(_context.getInputModel(), MetaAdapterFactory.getConcept(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, "JavaGuiLanguage.structure.Frame"))).translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getChildren(it, MetaAdapterFactory.getContainmentLink(0x48fa6eb61e164aa9L, 0x9b45ecc67f930903L, 0x27d4c529a7f1f5ffL, 0x27d4c529a7f41056L, "element"));
      }
    });
  }
}
